
USE [FRACTAL_UBIKATE]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[FUBI_SP_OBTENER_LISTA_ASISTENCIAS]
    @VC_IDENTIFICADOR_USUARIO VARCHAR(12),
    @CH_CODIGO_COMPANIA CHAR(4)
AS
BEGIN
    SELECT
        IN_SECUENCIAL,
        VC_IDENTIFICADOR_EMPLEADO,
        VC_NOMBRE_EMPLEADO,
        VC_LATITUD,
        VC_LONGITUD,
        CH_TIPO_ORIGEN,
        FORMAT(DT_FECHA_REGISTRO,'yyyyMMddHHmmss') AS DT_FECHA_REGISTRO,
        VC_DIRECCION
    FROM FUBI_TA_UBICATE_MARCAS
    WHERE FORMAT(DT_FECHA_REGISTRO,'yyyyMMdd')>FORMAT(DATEADD(DAY,-7,GETDATE()),'yyyyMMdd')
    AND VC_IDENTIFICADOR_EMPLEADO = @VC_IDENTIFICADOR_USUARIO
    AND CH_CODIGO_COMPANIA = @CH_CODIGO_COMPANIA
    ORDER BY IN_SECUENCIAL DESC
END  
